/*
 * usart_user.c
 *
 *  Created on: Dec 4, 2025
 *      Author: oscar
 */

#include "usart_user.h"

int uart_done = 1;

void usart1_init(void) {
	// enabled clock
	RCC->APB2ENR |= RCC_APB2ENR_USART1EN;

	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

	// TX PA9
	GPIOA->MODER &= ~GPIO_MODER_MODE9_0;
	GPIOA->MODER |= GPIO_MODER_MODE9_1;

	GPIOA->OTYPER &= ~GPIO_OTYPER_OT9;

	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR9_0;
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR9_1;

	GPIOA->PUPDR &= ~GPIO_PUPDR_PUPDR9_0;
	GPIOA->PUPDR &= ~GPIO_PUPDR_PUPDR9_1;

	GPIOA->AFR[1] |= GPIO_AFRH_AFSEL9_0;
	GPIOA->AFR[1] |= GPIO_AFRH_AFSEL9_1;
	GPIOA->AFR[1] |= GPIO_AFRH_AFSEL9_2;
	GPIOA->AFR[1] &= ~GPIO_AFRH_AFSEL9_3;
	// RX PA10
	GPIOA->MODER &= ~GPIO_MODER_MODE10_0;
	GPIOA->MODER |= GPIO_MODER_MODE10_1;

	GPIOA->OTYPER &= ~GPIO_OTYPER_OT10;

	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR10_0;
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR10_1;

	GPIOA->PUPDR &= ~GPIO_PUPDR_PUPDR10_0;
	GPIOA->PUPDR &= ~GPIO_PUPDR_PUPDR10_1;

	GPIOA->AFR[1] |= GPIO_AFRH_AFSEL10_0;
	GPIOA->AFR[1] |= GPIO_AFRH_AFSEL10_1;
	GPIOA->AFR[1] |= GPIO_AFRH_AFSEL10_2;
	GPIOA->AFR[1] &= ~GPIO_AFRH_AFSEL10_3;

	// setting parameters
	USART1->CR1 &= ~USART_CR1_UE;
	USART1->CR1 |= USART_CR1_UE; // enable USART1
	USART1->CR1 |= USART_CR1_RE;
	USART1->CR1 |= USART_CR1_TE;
	USART1->BRR = 0x0364; // 115200 baud @ 100 MHz
	USART1->CR2 &= ~USART_CR2_STOP_0; // 1 stop bit
	USART1->CR2 &= ~USART_CR2_STOP_1;
	//USART1->CR3 = 0x0000; // no flow control
	USART1->CR3 &= ~USART_CR3_CTSE;
	USART1->CR3 &= ~USART_CR3_RTSE;
	USART1->CR3 |= USART_CR3_DMAR;
	USART1->CR3 |= USART_CR3_DMAT;
	USART1->SR &= ~USART_SR_TC; // clear TC flag
	USART1->CR1 |= USART_CR1_TCIE;
	NVIC_EnableIRQ(USART1_IRQn); // NVIC
}

void usart1_IRQHandler(void) {
	uart_done = 1;
	// clear TC flag
	USART1->SR &= ~USART_SR_TC;
}
